In [1]:
import torch

In [11]:
"""
    Create the following tensors:
        1. 3D tensor of shape 20x30x40 with all values = 0
        2. 1D tensor containing the even numbers between 10 and 100
"""
#1. 3D tensor of shape 20x30x40 with all values = 0
#cách 1
tensor_3d = torch.zeros(20, 30, 40)
print(tensor_3d.shape)
print(tensor_3d.ndim)
print(tensor_3d.dtype)
print(tensor_3d.device)

#cách 2
tensor_3d = torch.full((20, 30, 40), 0)
print(tensor_3d.shape)
print(tensor_3d.ndim)
print(tensor_3d.dtype)
print(tensor_3d.device)

#2. 1D tensor containing the even numbers between 10 and 100
#cách 1 dùng torch.arange() với bước nhảy step=2
even_numbers = torch.arange(10, 101, 2)

#cách 2 tạo dãy rồi lọc
numbers = torch.arange(10, 101)
even_numbers = numbers[numbers % 2 == 0]
print(even_numbers)

torch.Size([20, 30, 40])
3
torch.float32
cpu
torch.Size([20, 30, 40])
3
torch.int64
cpu
tensor([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,  36,
         38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,  62,  64,
         66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,  88,  90,  92,
         94,  96,  98, 100])


In [12]:
"""
    x = torch.rand(4, 6)
    Calculate:
        1. Sum of all elements of x
        2. Sum of the columns of x  (result is a 6-element tensor)
        3. Sum of the rows of x   (result is a 4-element tensor)
"""
x = torch.rand(4, 6)
print(x)

# 1. Sum of all elements of x
total_sum = torch.sum(x)  # hoặc x.sum()
print("\nSum of all elements of x:", total_sum)

# 2. Sum of the columns of x
column_sums = torch.sum(x, dim=0)  # hoặc x.sum(dim=0)
print("\nSum of the columns of x:", column_sums)
print("Shape of colunm sum:", column_sums.shape)

# 3. Sum of the rows of x
row_sums = torch.sum(x, dim=1)  # hoặc x.sum(dim=1)
print("\nSum of the rows of x :", row_sums)
print("Shape of row sum:", row_sums.shape)

tensor([[0.3758, 0.2464, 0.7729, 0.5217, 0.9974, 0.3901],
        [0.9291, 0.7489, 0.8363, 0.4887, 0.7916, 0.9193],
        [0.3404, 0.3689, 0.8790, 0.6004, 0.6995, 0.7423],
        [0.2435, 0.6078, 0.4563, 0.2916, 0.3166, 0.2418]])

Sum of all elements of x: tensor(13.8064)

Sum of the columns of x: tensor([1.8889, 1.9719, 2.9445, 1.9024, 2.8052, 2.2935])
Shape of colunm sum: torch.Size([6])

Sum of the rows of x : tensor([3.3043, 4.7139, 3.6307, 2.1576])
Shape of row sum: torch.Size([4])


In [13]:
"""
    Calculate cosine similarity between 2 1D tensor:
    x = torch.tensor([0.1, 0.3, 2.3, 0.45])
    y = torch.tensor([0.13, 0.23, 2.33, 0.45])
"""
x = torch.tensor([0.1, 0.3, 2.3, 0.45])
y = torch.tensor([0.13, 0.23, 2.33, 0.45])

print("\n x tensor: ", x)
print("\n y tensor: ", y)

cosi = torch.nn.CosineSimilarity(dim=0) 
output = cosi(x, y)

print("\n Calculate cosine similarity between x and y: ", output)


 x tensor:  tensor([0.1000, 0.3000, 2.3000, 0.4500])

 y tensor:  tensor([0.1300, 0.2300, 2.3300, 0.4500])

 Calculate cosine similarity between x and y:  tensor(0.9995)


In [16]:
"""
    Calculate cosine similarity between 2 2D tensor:
    x = torch.tensor([[ 0.2714, 1.1430, 1.3997, 0.8788],
                      [-2.2268, 1.9799, 1.5682, 0.5850],
                      [ 1.2289, 0.5043, -0.1625, 1.1403]])
    y = torch.tensor([[-0.3299, 0.6360, -0.2014, 0.5989],
                      [-0.6679, 0.0793, -2.5842, -1.5123],
                      [ 1.1110, -0.1212, 0.0324, 1.1277]])
"""
x = torch.tensor([[ 0.2714, 1.1430, 1.3997, 0.8788],
                 [-2.2268, 1.9799, 1.5682, 0.5850],
                 [ 1.2289, 0.5043, -0.1625, 1.1403]])

y = torch.tensor([[-0.3299, 0.6360, -0.2014, 0.5989],
                 [-0.6679, 0.0793, -2.5842, -1.5123],
                 [ 1.1110, -0.1212, 0.0324, 1.1277]])

print("\nx tensor:", x)
print("\ny tensor:", y)

# Tính cosine similarity theo từng cột
cosi_0 = torch.nn.CosineSimilarity(dim=0)
output_0 = cosi_0(x, y)
print("\nCosine similarity between x and y in dim=0:", output_0)

# Tính cosine similarity theo từng hàng
cosi_1 = torch.nn.CosineSimilarity(dim=1)
output_1 = cosi_1(x, y)
print("\nCosine similarity between x and y in dim=1:", output_1)


x tensor: tensor([[ 0.2714,  1.1430,  1.3997,  0.8788],
        [-2.2268,  1.9799,  1.5682,  0.5850],
        [ 1.2289,  0.5043, -0.1625,  1.1403]])

y tensor: tensor([[-0.3299,  0.6360, -0.2014,  0.5989],
        [-0.6679,  0.0793, -2.5842, -1.5123],
        [ 1.1110, -0.1212,  0.0324,  1.1277]])

Cosine similarity between x and y in dim=0: tensor([ 0.8076,  0.5388, -0.7941,  0.3016])

Cosine similarity between x and y in dim=1: tensor([ 0.4552, -0.3140,  0.9258])


In [18]:
"""
    x = torch.tensor([[ 0,  1],
                      [ 2,  3],
                      [ 4,  5],
                      [ 6,  7],
                      [ 8,  9],
                      [10, 11]])
    Make x become 1D tensor
    Then, make that 1D tensor become 3x4 2D tensor 
"""
x = torch.tensor([[ 0,  1],
                 [ 2,  3],
                 [ 4,  5],
                 [ 6,  7],
                 [ 8,  9],
                 [10, 11]])

print("Original tensor x:")
print(x)
print("Shape:", x.shape)
print("ndim:", x.ndim)

# Make x become 1D tensor
x_1d = x.flatten()  # hoặc x.reshape(-1)
print("\nAfter flatten to 1D:")
print(x_1d)
print("Shape:", x_1d.shape)
print("ndim:", x_1d.ndim)

# 2. make that 1D tensor become 3x4 2D tensor 
x_2d = x_1d.reshape(3, 4)  # hoặc x_1d.view(3, 4)
print("\nAfter reshape to 3x4:")
print(x_2d)
print("Shape:", x_2d.shape)
print("ndim:", x_2d.ndim)

Original tensor x:
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])
Shape: torch.Size([6, 2])
ndim: 2

After flatten to 1D:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape: torch.Size([12])
ndim: 1

After reshape to 3x4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Shape: torch.Size([3, 4])
ndim: 2


In [19]:
"""
    x = torch.rand(3, 1080, 1920)
    y = torch.rand(3, 720, 1280)
    Do the following tasks:
        1. Make x become 1x3x1080x1920 4D tensor
        2. Make y become 1x3x720x1280 4D tensor
        3. Resize y to make it have the same size as x
        4. Join them to become 2x3x1080x1920 tensor
"""
import torch.nn.functional as F

x = torch.rand(3, 1080, 1920)
y = torch.rand(3, 720, 1280)

print("Original x shape:", x.shape)
print("Original y shape:", y.shape)

# 1. Biến x thành tensor 4D
x_4d = x.unsqueeze(0)  # Thêm chiều batch ở đầu
print("\nX shape after unsqueeze:", x_4d.shape)  # torch.Size([1, 3, 1080, 1920])

# 2. Biến y thành tensor 4D
y_4d = y.unsqueeze(0)  # Thêm chiều batch ở đầu
print("Y shape after unsqueeze:", y_4d.shape)  # torch.Size([1, 3, 720, 1280])

# 3. Resize y để có cùng kích thước với x
y_resized = F.interpolate(y_4d, size=(1080, 1920), mode='bilinear', align_corners=False)
print("Y shape after resize:", y_resized.shape)  # torch.Size([1, 3, 1080, 1920])

# 4. Ghép 2 tensor
combined = torch.cat([x_4d, y_resized], dim=0)
print("\nFinal combined shape:", combined.shape)  # torch.Size([2, 3, 1080, 1920])

Original x shape: torch.Size([3, 1080, 1920])
Original y shape: torch.Size([3, 720, 1280])

X shape after unsqueeze: torch.Size([1, 3, 1080, 1920])
Y shape after unsqueeze: torch.Size([1, 3, 720, 1280])
Y shape after resize: torch.Size([1, 3, 1080, 1920])

Final combined shape: torch.Size([2, 3, 1080, 1920])
